//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace courseBDWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class courseAndLevel
    {
        public string nameCourse { get; set; }
        public string nameLevel { get; set; }
        public int ID { get; set; }
    }
}
