//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace courseBDWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class courseAndTopic
    {
        public string nameCourse { get; set; }
        public int IDCourse { get; set; }
        public int numTopicInCourse { get; set; }
        public string nameTopic { get; set; }
    }
}
