//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace courseBDWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class courseTopic
    {
        public int ID { get; set; }
        public int IDCourse { get; set; }
        public int IDTopic { get; set; }
        public int numTopicInCourse { get; set; }
    
        public virtual course course { get; set; }
        public virtual topic topic { get; set; }
    }
}
