//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace courseBDWeb
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LearnEngEntities : DbContext
    {
        public LearnEngEntities()
            : base("name=LearnEngEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<course> course { get; set; }
        public virtual DbSet<courseLevel> courseLevel { get; set; }
        public virtual DbSet<courseTopic> courseTopic { get; set; }
        public virtual DbSet<topic> topic { get; set; }
        public virtual DbSet<courseAndLevel> courseAndLevel { get; set; }
        public virtual DbSet<courseAndTopic> courseAndTopic { get; set; }
    }
}
